name: the_api

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  async: any
  http: any
  json_annotation: ^3.0.1
  path: ^1.6.4

dev_dependencies:
  build_runner: ^1.8.0
  json_serializable: ^3.2.5
  test: ^1.3.3
