name: tinhte_api

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  async: ^2.0.8
  http: any
  json_annotation: ^1.0.0
  path: ^1.6.2

dev_dependencies:
  build_runner: ^0.10.0
  json_serializable: ^1.4.0
  test: ^1.3.3
