on: push
name: iOS IPA
env:
  GCS_BUCKET: flutterttdemo

jobs:
  build:
    name: Build IPA
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - run: git submodule update --init --recursive
    - name: Unlock git-crypt
      run: |
        set -e
        
        brew install git-crypt
        
        # https://github.com/sliteteam/github-action-git-crypt-unlock/blob/master/entrypoint.sh
        echo $GIT_CRYPT_KEY | base64 --decode > ./git-crypt-key
        git-crypt unlock ./git-crypt-key
        rm ./git-crypt-key
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
    - name: Extract Flutter version from pubspec.yaml
      id: yq
      run: |
        set -e

        brew install yq
        _flutterVersion=$( yq read pubspec.yaml environment.flutter )
        echo "::set-output name=FLUTTER_VERSION::$_flutterVersion"

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ steps.yq.outputs.FLUTTER_VERSION }}

    - run: flutter pub get
    - run: flutter build ios --no-codesign
    - run: cd ios && fastlane ipa

    - name: Setup gsutil
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_UPLOADER_SA_KEY }}
    - run: gsutil cp build/app/outputs/ipa/release/* gs://${GCS_BUCKET}/${GITHUB_SHA}/ipa

  comment:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Post GitHub comment
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "[Built IPA](itms-services://?action=download-manifest&url=https://storage.cloud.google.com/${GCS_BUCKET}/${GITHUB_SHA}/ipa/manifest.plist)"
