on: push
name: iOS IPA
jobs:
  build:
    name: Build IPA
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - run: git submodule update --init --recursive
    - name: Unlock git-crypt
      run: |
        set -e
        
        brew install git-crypt
        
        # https://github.com/sliteteam/github-action-git-crypt-unlock/blob/master/entrypoint.sh
        echo $GIT_CRYPT_KEY | base64 --decode > ./git-crypt-key
        git-crypt unlock ./git-crypt-key
        rm ./git-crypt-key
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
    - name: Extract Flutter version from pubspec.yaml
      id: yq
      run: |
        set -e

        brew install yq
        _flutterVersion=$( yq read pubspec.yaml environment.flutter )
        echo "::set-output name=FLUTTER_VERSION::$_flutterVersion"

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ steps.yq.outputs.FLUTTER_VERSION }}

    - run: flutter pub get
    - run: flutter build ios --no-codesign

    - name: Create a GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: build/ios/iphoneos/Runner.app
        token: ${{ secrets.TOKEN }}
    - uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags/') != true
      with:
        name: Runner.app
        path: build/ios/iphoneos/Runner.app
